#!/usr/bin/env bash
set -e
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
VER="$(tools/release/version.sh)"
OUT="${1:-dist/release/RELEASE_NOTES.md}"
mkdir -p "$(dirname "$OUT")"
{
  echo "# Execution Lab — Release $VER"
  echo
  echo "Automated release artifact generated by CI (Phase 11 skeleton)."
  echo
  echo "## Version"
  echo "- \`$VER\`"
  echo
  echo "## Tags"
  git --no-pager tag --points-at HEAD || true
  echo
  echo "## Commit"
  git --no-pager show -s --format='- %h %s (%ad)' --date=short HEAD
} > "$OUT"
echo "WROTE: $OUT"
