#!/usr/bin/env bash
set -e
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

mkdir -p dist/release

echo "=== RELEASE DRILL (local, no network) ==="

# must have gates from earlier phases
test -f tools/phase11_gate.sh
test -f tools/phase13_gate.sh
test -f tools/phase14_gate.sh

# ensure git clean (drill expects disciplined release)
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree not clean. Commit Phase 15 first."
  git status --short
  exit 1
fi

VER="$(tools/release/version.sh)"
TAG="v$VER"

# tauri config version must match VERSION
python3 - <<PY2
import json
conf="el_gui/src-tauri/tauri.conf.json"
d=json.load(open(conf,"r",encoding="utf-8"))
v=d.get("version","")
import sys
if v != "$VER":
    print(f"ERROR: tauri.conf.json version={v} != VERSION=$VER")
    sys.exit(1)
print("OK: tauri.conf.json version matches VERSION")
PY2

# ensure updater endpoint points to latest.json + pubkey exists
rg -n 'releases/latest/download/latest\.json' el_gui/src-tauri/tauri.conf.json >/dev/null
rg -n '"createUpdaterArtifacts"\s*:\s*true' el_gui/src-tauri/tauri.conf.json >/dev/null
rg -n '"pubkey"\s*:\s*"' el_gui/src-tauri/tauri.conf.json >/dev/null

# secrets are referenced in workflow
rg -n 'TAURI_SIGNING_PRIVATE_KEY' .github/workflows/release.yml >/dev/null
rg -n 'mk_latest_json\.sh' .github/workflows/release.yml >/dev/null
rg -n 'dist/release/latest\.json' .github/workflows/release.yml >/dev/null

# keys discipline
test -f keys/tauri_updater.key.pub
rg -n '^/keys/tauri_updater\.key$' .gitignore >/dev/null

# run prior gates (fast)
tools/phase11_gate.sh >/dev/null
tools/phase13_gate.sh >/dev/null
tools/phase14_gate.sh >/dev/null

# build report
SLUG="$(tools/release/repo_slug.sh 2>/dev/null || true)"
if [ -z "$SLUG" ] || [ "$SLUG" = "UNKNOWN/UNKNOWN" ]; then SLUG="hellaraze/execution-lab"; fi

cat > dist/release/DRILL_REPORT.md <<EOF2
# Release Drill Report

- VERSION: $VER
- TAG: $TAG
- Repo: $SLUG
- Updater endpoint: https://github.com/$SLUG/releases/latest/download/latest.json

## What CI will produce on a release run
- Windows bundle(s): dist/phase7/windows/bundle/** (uploaded as artifacts + attached to GitHub Release)
- Release notes: dist/release/RELEASE_NOTES.md
- Updater feed: dist/release/latest.json
- Installer signature: generated by Tauri build when TAURI_SIGNING_PRIVATE_KEY is set (\*.sig)

## Required GitHub Secrets
- TAURI_SIGNING_PRIVATE_KEY
- TAURI_SIGNING_PRIVATE_KEY_PASSWORD (optional)

## Operator steps (manual)
1) Ensure VERSION is correct (and tauri.conf.json version matches).
2) Create annotated tag: $TAG
3) Run GitHub Actions workflow "release" with input tag=$TAG
4) Verify GitHub Release assets include installer + latest.json

EOF2

echo "WROTE: dist/release/DRILL_REPORT.md"
echo "DRILL_OK"
